#!/usr/bin/env python3
"""Generate bounded ABI-model properties from the exact TLA invariant ledger."""

import argparse
import difflib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "formal/byte_values_v2_ledger.json"
OUTPUT = ROOT / "tests/generated/byte_values_v2_properties.rs"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    ledger = json.loads(LEDGER.read_text())
    model = (ROOT / ledger["model"]).read_text()
    names = [row["name"] for row in ledger["invariants"]]
    properties = [row["property"] for row in ledger["invariants"]]
    if len(names) != len(set(names)) or len(properties) != len(set(properties)):
        raise SystemExit("duplicate invariant or property in ledger")
    for name in names:
        if not re.search(rf"^{re.escape(name)} ==", model, re.MULTILINE):
            raise SystemExit(f"ledger invariant missing from TLA model: {name}")
    for cfg in sorted((ROOT / "formal/MC").glob("ByteValueDictionaryV2*.cfg")):
        text = cfg.read_text()
        match = re.search(r"^INVARIANTS\n((?:  [A-Za-z][A-Za-z0-9]*\n)+)", text, re.MULTILINE)
        if match is None:
            raise SystemExit(f"missing invariant list: {cfg}")
        actual = [line.strip() for line in match.group(1).splitlines()]
        if actual != names:
            raise SystemExit(f"invariant list differs from ledger: {cfg}")
    if set(names) != {
        "TypeOK", "CapabilitySound", "NoByteValueErasure", "SnapshotPinned",
        "TokenAuthority", "CopyAtomic", "PageBounded", "LeaseGenerationSound",
        "CancellationSticky", "NoPerKeyDispatch",
    }:
        raise SystemExit("invariant ledger is incomplete or unexpected")
    seeds = ledger["seed_count"]
    if not isinstance(seeds, int) or not 1 <= seeds <= 256:
        raise SystemExit("seed_count must be in 1..256")

    lines = [
        "// Generated by scripts/generate-byte-values-v2-properties.py; do not edit.",
        "// Each test maps one TLA invariant to bounded property cases over the ABI model.",
        "",
    ]
    for name, prop in zip(names, properties, strict=True):
        lines.extend([
            "#[test]",
            f"fn {prop}() {{",
            f"    for seed in 0u8..{seeds} {{",
            f'        check_generated_property("{name}", seed);',
            "    }",
            "}",
            "",
        ])
    expected = "\n".join(lines)
    if args.check:
        actual = OUTPUT.read_text() if OUTPUT.exists() else ""
        if actual != expected:
            diff = "".join(difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(OUTPUT),
                tofile="generated expected",
            ))
            raise SystemExit(diff or "generated properties are stale")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected)


if __name__ == "__main__":
    main()
